### ISSUE TITLE
Comment comparer ?

### ISSUE THREAD

**Issue by omartineau** [alphoenix/donnees#4]
Il serait interessant d'avoir le même genre de statistiques avec d'autres grands secteurs comme : 
- la pharmacie,
- l'énergie,
- l'automobile,
- la finanance,
- l'industrie agroalimentaire,
- etc.

**Comment by alphoenix** [comment]
Oui, toutes les données sont tirées d'[Integrity Watch](http://www.integritywatch.eu/) qui permettra de se faire une idée pour quelques entreprises. Où l'on voit que Google est la deuxième entreprise en terme de rencontres, toutes entreprises confondues.
Si on me finance, je peux faire la même chose 😉
