### ISSUE TITLE
Investitures PS en html

### ISSUE THREAD

**Issue by RouxRC** [alphoenix/donnees#7]
Salut Alexandre, je n'avais pas trouvé les investitures des autres partis quand je l'ai fait, mais il y a celles du PS en html ici : http://www.parti-socialiste.fr/liste-candidats-aux-legislatives-investis-ps/
Ça évite d'avoir à utiliser tabula et permet d'automatiser le suivi et de voir disparaître Bartolone par exemple :)
https://github.com/RouxRC/investitures-PS-2017

**Comment by alphoenix** [comment]
Ah oui, ça a l'air pas mal comme ça, et ça permet effectivement de suivre les modifs, je vais me pencher sur ton script. Il semble qu'il y ait un petit souci dans le nom des circos (j'ai regardé que Paris).

**Comment by RouxRC** [comment]
Ah oui bien vu! Apparemment je ne prenais que le dernier chiffre du numéro de circo à chaque fois, ce qui fait des doublons pour les départements avec plus de 10 circos, je corrige ça

**Comment by RouxRC** [comment]
@alphoenix ça y est les macronistes sont désinvestis ;) https://github.com/RouxRC/investitures-PS-2017/commit/e6e7d73f054e1e2d13a7126f513dd14ecf0c4784
